#!/bin/sh

# Цветастый текст
NORMAL='\033[0m';
BLACK='\033[0;30m';
RED='\033[0;31m';
GREEN='\033[0;32m';
YELLOW='\033[0;33m';
BLUE='\033[0;34m';
MAGENTA='\033[0;35m;'
CYAN='\033[0;36m';
GRAY='\033[0;37m';

# Релизная ветка
PROTECTED_BRANCH='master';

# Текущая ветка
CURRENT_BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,');

# Если ветка релизная — делаем дела
if [[ "${CURRENT_BRANCH}" = "${PROTECTED_BRANCH}" ]]; then
    echo -e "${RED}Коммитить в ${PROTECTED_BRANCH} нельзя!${NORMAL}";
    exit 1;
fi;

exit 0;
